### ISSUE TITLE
Question regarding SSID broadcast

### ISSUE THREAD

**Issue by mbennett** [scott-linenberger/iot_status_indicator#5]
Scott, I can't figure out how to stop broadcasting the SSID.  Do you have any idea how this can be done in the iot_status_indicator sketch?

**Comment by scott-linenberger** [comment]
Broadcasting the SSID? You'll have to elaborate.

**Comment by mbennett** [comment]
When I open Wi-Fi configuration (on a Mac) the Adafruit Feather Huzzah device is shown in the list of Wi-Fi access points as ESP_XXXXXX.  I found some documentation at https://arduino-esp8266.readthedocs.io/en/2.5.1/esp8266wifi/readme.html that might shed some light on the topic.

**Comment by scott-linenberger** [comment]
Interesting. I've never noticed this before. I didn't actually write the connection code or the code that manages the Adafruit IO connection. That comes from Adafruit's libraries. I don't think it harms anything, but it probably isn't good to have an open connection like that. You should log an issue with: https://github.com/adafruit/Adafruit_IO_Arduino -- if they update their library, I can update this code and the issue should go away.
